#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0.30
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: ss
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10
##    volumes:
##      - ./mysql-data:/var/lib/mysql
#
#  app:
#    image: busticketsystem1
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ss?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=
